spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: pets
      username: user
      password: abc123
      database: rest_tutorial
      uri: mongodb://127.0.0.1:27017/pets